services:
    influxdb2:
        image: influxdb:2-alpine
        ports:
            - 8086:8086
        environment:
            DOCKER_INFLUXDB_INIT_MODE: setup
            DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
            DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
            DOCKER_INFLUXDB_INIT_ORG: home
            DOCKER_INFLUXDB_INIT_BUCKET: test
        secrets:
            - influxdb2-admin-username
            - influxdb2-admin-password
            - influxdb2-admin-token
        volumes:
            - type: volume
              source: influxdb2-data
              target: /var/lib/influxdb2
            - type: volume
              source: influxdb2-config
              target: /etc/influxdb2
            - type: bind
              source: ./influxdb2-initscripts
              target: /docker-entrypoint-initdb.d
              read_only: true
secrets:
    influxdb2-admin-username:
        file: ./influxdb2-admin-username.secret
    influxdb2-admin-password:
        file: ./influxdb2-admin-password.secret
    influxdb2-admin-token:
        file: ./influxdb2-admin-token.secret
volumes:
    influxdb2-data:
    influxdb2-config:
